name: CI ProFuturo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Lint
        run: npm run lint || true
      - name: Testes
        run: npm test || true
      - name: Build
        run: npm run build || true

  aluno:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/aluno
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Lint
        run: npm run lint || true
      - name: Testes
        run: npm test || true
      - name: Build
        run: npm run build || true

  professor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/professor
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Lint
        run: npm run lint || true
      - name: Testes
        run: npm test || true
      - name: Build
        run: npm run build || true 